### ISSUE TITLE
RFE: revoking standalone license 

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-declarative-onboarding#58] opened 2019-08-13 18:26 UTC
Similar to revoking from BIG-IQ it would be desirable to revoke a standalone license.

```
curl -v -k -s -u admin:admin -H "Content-Type: application/json" -d '{"command":"revoke"}' -X POST https://192.168.1.245/mgmt/tm/sys/license
```
I believe this is supported in 13.1+?

**Comment by dstokesf5** [comment] 2019-11-12 17:16
When I try to revoke a  license through the supplied iControl REST request, I get the following response:
```json
{
    "kind": "tm:sys:license:revokestate",
    "command": "revoke",
    "commandResult": "\n***Error: Cannot determine IP for license server.\n\n"
}
```

I also get a similar result from `tmsh revoke sys license`:
```
***Error: Cannot determine IP for license server.
```

Can you provide some additional documentation on this functionality and when it can be used?

**Comment by chen23** [comment] 2019-11-12 17:24
Make sure you are using a production or eval license key. That error is usually related to the use of internal resources.

**Comment by dstokesf5** [comment] 2019-11-12 20:03
That was my problem, the iControl REST command worked as expected with an eval license. Can you please elaborate on the use case for revoking a standalone license and why you need this feature?

**Comment by chen23** [comment] 2019-11-12 23:22
For license mobility you need to revoke a license before it can be applied to another device.

**Comment by kreynoldsf5** [comment] 2020-08-16 15:58
Bump.

It would not be uncommon for devs to programmatically spin up and tear down BIG-IP instances with Prod or Eval licenses with frequency. This activity should be supported:

- without needing BIG-IQ License Manager
- without contacting support to have a license renewed/refreshed 
- through the same interface being used to onboard the device (ie. we should not expect customers to use an out of band iCR call prior to destroying an instance)

**Comment by dstokesf5** [comment] 2020-11-13 16:18
Closing as duplicate of #9. @kreynoldsf5, I have added your comment to AUTOTOOL-118.

**Closed by dstokesf5** 2020-11-13 16:18 UTC
Labels: enhancement, untriaged

**Comment by mdditt2000** [comment] 2023-03-27 17:36
Support for revoking license on a BIG-IP coming in F5 Declarative Onboarding 1.38. Message me if you require early version of this release.
