### ISSUE TITLE
Upgrading DO from 15 to 19 caused transaction failure based on identifiers

### ISSUE THREAD

**Issue by focrensh** [F5Networks/f5-declarative-onboarding#209] opened 2021-03-03 20:47 UTC
### Environment
 * Declarative Onboarding Version: 1.19
 * BIG-IP Version: 14.1.2

### Summary
BIG-IP was running 1.14 with the declaration below. After upgrading to 1.19, the errors below occured. This errors persisted even after using `clear-rest-storage`, reinstalling the extension, and re-declaring.

Downgraded to 1.15 and the issue went away.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "schemaVersion": "1.0.0",
    "class": "Device",
    "async": true,
    "Common": {
        "class": "Tenant",
        "hostname": "test-bip.local"
    }
}
```

2. Observe the following error response:
```json
"errors": [
 "one or more properties must be specified",
 "transaction failed:one or more configuration identifiers must be provided"
 ],
 "result": {
```

### Expected Behavior
Success

### Actual Behavior
Previously working declaration now causes an error.

**Comment by dstokesf5** [comment] 2021-03-09 22:11
Looks like this one is a duplicate of #190. Closing this one since we have some good notes on #190 in our internal ticket for it.

**Closed by dstokesf5** 2021-03-09 22:11 UTC
Labels: bug, untriaged
