### ISSUE TITLE
modifying mgmt interface

### ISSUE THREAD

**Issue by jackyatesaustin** [F5Networks/f5-declarative-onboarding#183] opened 2020-11-03 21:13 UTC
### Is your feature request related to a problem? Please describe.
create sys management-ip <IP-address>
modify net interface mgmt media auto
Commands like these are not available in DO. Ask is that these be added.

### Describe the solution you'd like
For the above commands to be made available in DO

### Describe alternatives you've considered
n/a

**Comment by dstokesf5** [comment] 2021-09-15 18:44
It looks like changing the media property is a duplicate of #166.

Configuration of the management IP was added in release 1.23.0.

**Closed by dstokesf5** 2021-09-15 18:44 UTC
Labels: enhancement, untriaged
