### ISSUE TITLE
Add the ability to create static MGMT IP for use with tmos_declared

### ISSUE THREAD

**Issue by thomsonjames** [F5Networks/f5-declarative-onboarding#212] opened 2021-03-24 17:25 UTC
We use the tmos_declared feature in BIG-IP which allows us to provide a DO declaration in cloud-init.
https://clouddocs.f5.com/cloud/public/v1/shared/cloudinit.html#cloudconfig-tmosdecl

I would like to be able to define a static management IP address in here.
Ideally, if one is configured, sys global-settings mgmt-dhcp would be automatically changed to disabled
sys global-settings {
    mgmt-dhcp disabled
}

This feature would be useful for Private cloud environments where networks already exist and do not have DHCP.

**Comment by drennalls** [comment] 2021-03-30 15:28
I agree. There's a [tmos_static_mgmt Cloudinit Module]( https://github.com/f5devcentral/tmos-cloudinit#the-tmos_static_mgmt-cloudinit-module) which can be bundled by patching the BIGIP image, but it would be nice if this was part of the default set of modules.

**Comment by dstokesf5** [comment] 2021-04-28 19:47
Declarative Onboarding has a ManagementRoute class that you can see used in this example: https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/declarations/basic.html#standalone-declaration

If this class does not configure what you need, can you please provide some example tmsh configuration of what you want Declarative Onboarding to do?

**Comment by dstokesf5** [comment] 2021-04-28 19:55
I did not realize that there is a separate `sys management-ip` object that is not configured by Declarative Onboarding's ManagementRoute class.

**Comment by dstokesf5** [comment] 2021-04-28 19:58
This issue is a duplicate of #224. Closing this one since #224 provides additional context.

**Closed by dstokesf5** 2021-04-28 19:58 UTC
Labels: enhancement, untriaged
