### ISSUE TITLE
GENEVE tunnel support

### ISSUE THREAD

**Issue by grf5** [F5Networks/f5-declarative-onboarding#256] opened 2021-08-23 10:32 UTC
### Is your feature request related to a problem? Please describe.
I need GENEVE tunnel type support for AS3. This is required to enable AS3 to interact with the new AWS Gateway Load Balancer (GWLB) functionality. (See https://devcentral.f5.com/s/articles/BIGIP-integration-with-AWS-Gateway-Load-Balancer-Overview)

### Describe the solution you'd like
Currently DO only supports tunnels of type "tcp-forward." (https://clouddocs.f5.com/cli/tmsh-reference/v15/modules/net/net_tunnels_tcp-forward.html). 

For GWLB, GENEVE is required. (See https://clouddocs.f5.com/cli/tmsh-reference/v15/modules/net/net_tunnels_geneve.html)

### Describe alternatives you've considered
Currently using TMSH commands inside of bigip-runtime-init instead of using DO to create the tunnel configuration. Note the use of route domain notation.

```console
tmsh create net tunnels tunnel geneve local-address `printf {{{ MGMT_IP }}} | cut -d \"/\" -f1`%1 remote-address any%1 profile geneve
```

**Comment by dstokesf5** [comment] 2021-09-14 20:11
Closing as a duplicate of #206

**Closed** 2021-09-14 20:11 UTC
Labels: duplicate, enhancement
