### ISSUE TITLE
java.util.concurrent.TimeoutException: remoteSender:45.20.30.148, method:POST

### ISSUE THREAD

**Issue by codygreen** [F5Networks/f5-declarative-onboarding#68] opened 2019-09-04 23:38 UTC
##### ISSUE TYPE

 - Bug Report

##### DO BUILD/ VERSION
```
1.5.0-11 and 1.6.0-1
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.1.4
  Build       0.0.4
  Edition     Point Release 4
  Date        Wed Jan 16 18:04:36 PST 2019
```

##### SUMMARY

```
Declaration fails with a 400 response code and a java stack trace
```

##### STEPS TO REPRODUCE

```
{
    "schemaVersion": "1.5.0",
    "class": "Device",
    "async": true,
    "Common": {
        "class": "Tenant",
        "hostname": "demo",
        "myLicense": {
            "class": "License",
            "licenseType": "licensePool",
            "bigIqHost": "****",
            "bigIqUsername": "****",
            "bigIqPassword": "****",
            "licensePool": "rs_subscription",
            "skuKeyword1": "AWF",
            "skuKeyword2": "1G",
            "unitOfMeasure": "yearly",
            "reachable": false,
            "hypervisor": "azure"
        },
        "myDns": {
            "class": "DNS",
            "search": [
                "f5.com",
                "test.com"
            ]
        },
        "myProvisioning": {
            "class": "Provision",
            "ltm": "nominal",
            "asm": "nominal"
        },
        "ext": {
            "class": "VLAN",
            "tag": 1234,
            "mtu": 1500,
            "interfaces": [{
                "name": "1.1",
                "tagged": false
            }]
        },
        "ext-self": {
            "class": "SelfIp",
            "address": "10.90.2.8/24",
            "vlan": "ext",
            "allowService": "all",
            "trafficGroup": "traffic-group-local-only"
        },
        "ext_gw": {
            "class": "Route",
            "gw": "10.90.2.1",
            "network": "default",
            "mtu": 1500
        }
    }
}
```

##### EXPECTED RESULTS

```
Should onboard BIG-IP with license from BIG-IQ
```

##### ACTUAL RESULTS

```
#HTTP Response
{
    "code": 400,
    "message": "remoteSender:45.20.30.148, method:POST ",
    "originalRequestBody": "{\n    \"schemaVersion\": \"1.5.0\",\n    \"class\": \"Device\",\n    \"async\": true,\n    \"Common\": {\n        \"class\": \"Tenant\",\n        \"hostname\": \"wmt.demo\",\n        \"myLicense\": {\n            \"class\": \"License\",\n            \"licenseType\": \"licensePool\",\n            \"bigIqHost\": \"calalang-bigiq.westus2.cloudapp.azure.com\",\n            \"bigIqUsername\": \"licensor\",\n            \"bigIqPassword\": \"PlaintextPassword1$\",\n            \"licensePool\": \"rs_subscription\",\n            \"skuKeyword1\": \"AWF\",\n            \"skuKeyword2\": \"1G\",\n            \"unitOfMeasure\": \"yearly\",\n            \"reachable\": false,\n            \"hypervisor\": \"azure\"\n        },\n        \"myDns\": {\n            \"class\": \"DNS\",\n            \"search\": [\n                \"f5.com\",\n                \"test.com\"\n            ]\n        },\n        \"myProvisioning\": {\n            \"class\": \"Provision\",\n            \"ltm\": \"nominal\",\n            \"asm\": \"nominal\"\n        },\n        \"ext\": {\n            \"class\": \"VLAN\",\n            \"tag\": 1234,\n            \"mtu\": 1500,\n            \"interfaces\": [{\n                \"name\": \"1.1\",\n                \"tagged\": false\n            }]\n        },\n        \"ext-self\": {\n            \"class\": \"SelfIp\",\n            \"address\": \"10.90.2.8/24\",\n            \"vlan\": \"ext\",\n            \"allowService\": \"all\",\n            \"trafficGroup\": \"traffic-group-local-only\"\n        },\n        \"ext_gw\": {\n            \"class\": \"Route\",\n            \"gw\": \"10.90.2.1\",\n            \"network\": \"default\",\n            \"mtu\": 1500\n        }\n    }\n}",
    "referer": "45.20.30.148",
    "restOperationId": 43686,
    "errorStack": [
        "java.util.concurrent.TimeoutException: remoteSender:45.20.30.148, method:POST ",
        "at com.f5.rest.common.RestWorker.logAndFailExpiredOperation(RestWorker.java:3099)",
        "at com.f5.rest.common.RestWorker.checkForExpiredOperations(RestWorker.java:3088)",
        "at com.f5.rest.common.RestServer.checkAndExpirePendingWorkerOperations(RestServer.java:1457)",
        "at com.f5.rest.common.RestServer.access$400(RestServer.java:48)",
        "at com.f5.rest.common.RestServer$4.run(RestServer.java:1430)",
        "at com.f5.rest.common.ScheduleTaskManager$2$1.run(ScheduleTaskManager.java:123)",
        "at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)",
        "at java.util.concurrent.FutureTask.run(FutureTask.java:262)",
        "at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)",
        "at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)",
        "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)",
        "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)",
        "at java.lang.Thread.run(Thread.java:748)\n"
    ],
    "kind": ":resterrorresponse"
}

#restnoded log clip:
Wed, 04 Sep 2019 23:28:24 GMT - severe: [RestOperationDispatcher] 'shared/declarative-onboarding' not found.
Wed, 04 Sep 2019 23:28:24 GMT - severe: [ErrorHandlingModule] RestOperation failed: "/shared/declarative-onboarding". {"error":{"code":404,"message":"","innererror":{"referer":"restnoded","originalRequestBody":"{\"schemaVersion\":\"1.5.0\",\"class\":\"Device\",\"async\":true,\"Common\":{\"class\":\"Tenant\",\"hostname\":\"wmt.demo\",\"myLicense\":{\"class\":\"License\",\"licenseType\":\"licensePool\",\"bigIqHost\":\"calalang-bigiq.westus2.cloudapp.azure.com\",\"bigIqUsername\":\"licensor\",\"bigIqPassword\":\"PlaintextPassword1$\",\"licensePool\":\"rs_subscription\",\"skuKeyword1\":\"AWF\",\"skuKeyword2\":\"1G\",\"unitOfMeasure\":\"yearly\",\"reachable\":false,\"hypervisor\":\"azure\"},\"myDns\":{\"class\":\"DNS\",\"search\":[\"f5.com\",\"test.com\"]},\"myProvisioning\":{\"class\":\"Provision\",\"ltm\":\"nominal\",\"asm\":\"nominal\"},\"ext\":{\"class\":\"VLAN\",\"tag\":1234,\"mtu\":1500,\"interfaces\":[{\"name\":\"1.1\",\"tagged\":false}]},\"ext-self\":{\"class\":\"SelfIp\",\"address\":\"10.90.2.8/24\",\"vlan\":\"ext\",\"allowService\":\"all\",\"trafficGroup\":\"traffic-group-local-only\"},\"ext_gw\":{\"class\":\"Route\",\"gw\":\"10.90.2.1\",\"network\":\"default\",\"mtu\":1500}}}","errorStack":[]}}}
Wed, 04 Sep 2019 23:28:24 GMT - finest: [RestjavadMonitor] http://localhost:8100/shared/identified-devices/config/device-info unavailable: socket hang up
```

**Comment by codygreen** [comment] 2019-09-04 23:52
This VM obtains the DNS nameserver via DHCP.  Leaving the nameServers attribute off the declaration seems to cause the problem.  You should be able to not set the DNS server and the declaration still work.

When I add a nameServers attribute I don't recieve this error:
`"myDns": {
                "class": "DNS",
                "nameServers": [
                    "168.63.129.16"
                ],
                "search": [
                    "f5.com",
                    "test.com"
                ]
            },`

**Comment by dstokesf5** [comment] 2019-11-06 20:04
I was unable to reproduce this bug with my local environment. Are you still seeing this issue with DO v1.8.0?

**Comment by codygreen** [comment] 2019-11-12 22:15
No, I have not been able to reproduce this since the hotfix was given to me.

**Comment by dstokesf5** [comment] 2019-11-12 22:16
Thanks, closing this issue.

**Closed by dstokesf5** 2019-11-12 22:16 UTC
Labels: question
