### ISSUE TITLE
BIG-IQ License with VE 1NIC

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-declarative-onboarding#40] opened 2019-05-24 15:04 UTC
After multiple variants in declarations, DO BIG-IQ license support is not working for VE 1NIC in our environment. When a licensing request is made to BIG-IQ, with the reachable attribute defined as true or false, DO is producing the following error message:

```
"errors": [
        "Device at [onenic selfip address] is not reachable. Please ensure that you've entered the correct IP address and restjavad services on the device are running."
    ],
```
The error message is actually being proxied from BIG-IQ, which is very confusing. It is BIG-IQ which is stating the device can not be reached.

restnoded.log (which has all the discovered device information) and a sample declaration which produced the log are available:

[https://www.dropbox.com/s/hdo3r66o110rzde/1nic_bigiq_license_artifacts.tar.gz](1nic_bigiq_license_artifacts.tar.gzl)

**Comment by jgruber** [comment] 2019-05-24 15:27
Error from the BIG-IQ log:

```
[INFO][24 May 2019 09:05:36 CDT][/shared/authn/login AuthnWorker] User admin successfully logged in from 192.168.245.111 using the local authentication provider.
[ERROR][24 May 2019 09:05:40 CDT][/cm/device/licensing/pool/regkey/licenses/8089d162-fa2e-45fd-a826-c3890ed3fccf/offerings/YKUTH-UAMTQ-BHQAI-DHWFZ-MXRUXDF/members RegkeyPoolLicenseMemberCollectionWorker] regkey license 8089d162-fa2e-45fd-a826-c3890ed3fccf, offering YKUTH-UAMTQ-BHQAI-DHWFZ-MXRUXDF: Device at 192.168.245.111 is not reachable. Please ensure that you've entered the correct IP address and restjavad services on the device are running.: java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:173)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:147)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:350)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:191)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
        at java.lang.Thread.run(Thread.java:748)

```
Appears that BIG-IQ is trying to talk on port 443.. which won't work.

Licensing from BIG-IQ using port 8443 works just fine.

Seems we need bigIpTargetHost and bigIpTargetPort in the License class to support BIG-IQ licensing through NATs and on various ports (because of 1NIC or port proxies).

**Comment by focrensh** [comment] 2019-05-28 14:22
AT-361 opened for tracking

**Comment by seattlevine** [comment] 2019-05-30 19:46
I cannot reproduce this. Questions:
- What version of BIG-IP?
- What version of BIG-IQ?
- What type of license pool (utility, reg key)?

**Comment by jgruber** [comment] 2019-05-31 13:35
BIG-IP 14.1
BIG-IQ 6.1
REGKEY pool. 

You can see the TMOS version and the pool license type in the log outputs.

**Comment by jgruber** [comment] 2019-06-01 01:05
Mike.. I can reproduce this with OpenStack, libvirt on a linux host, and VMware workstation. Same error proxied from BIG-IQ:

"Unable to assign license; Device at 192.168.0.100 is not reachable. Please ensure that you've entered the correct IP address and restjavad services on the device are running."

Again.. If I go to BIG-IQ and issue an unmanaged device license to the IP address in the error message on port 8443, the licensing process works properly.

**Comment by seattlevine** [comment] 2019-06-01 05:06
We can reproduce this now. It only affect reg key pools. We’ll have it fixed in our next release.

**Comment by jgruber** [comment] 2019-06-12 13:44
Confirmed f5-declarative-onboarding-1.5.0-8.noarch.rpm allows for 1NIC and BIG-IQ REGKEY pools to work. Thank you!

**Closed** 2019-06-17 23:27 UTC
Labels: InReview, bug
