### ISSUE TITLE
BIG-IQ licensing with reachable: false does not work

### ISSUE THREAD

**Issue by thomsonjames** [F5Networks/f5-declarative-onboarding#47] opened 2019-06-26 16:36 UTC
When using the DO licensing option of "reachable": false", it seems that DO ignores this setting and provides an error saying it cannot reach the BIG-IP.

I get the error
<snippet>
Device at 192.168.10.9 is not reachable. Please ensure that you've entered the correct IP address and restjavad services on the device are running
</snippet>

Here is the declaration
`{
	"$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/schema/base.schema.json",
    "schemaVersion": "1.5.0",
    "class": "Device",
    "Common": {
      "class": "Tenant",
      "provisioningLevels": {
        "class": "Provision",
        "ltm": "nominal"
      },
      "hostname": "bigipos.jthomsonf5.com",
      "myLicense": {
        "class": "License",
        "licenseType": "licensePool",
        "bigIqHost": "10.1.0.227",
        "bigIqUsername": "admin",
        "bigIqPassword": "admin",
        "licensePool": "keypool",
        "reachable": false,
        "hypervisor": "kvm"
        }
    }
}`

I get the error

{
    "id": "e0d97a51-fc01-41e4-b4de-0cfb148c4dd4",
    "selfLink": "https://localhost/mgmt/shared/declarative-onboarding/task/e0d97a51-fc01-41e4-b4de-0cfb148c4dd4",
    "code": 422,
    "status": "ERROR",
    "message": "invalid config - rolled back",
    "errors": [
        "Device at 192.168.10.9 is not reachable. Please ensure that you've entered the correct IP address and restjavad services on the device are running."
    ],
    "result": {
        "class": "Result",
        "code": 422,
        "status": "ERROR",
        "message": "invalid config - rolled back",
        "errors": [
            "Device at 192.168.10.9 is not reachable. Please ensure that you've entered the correct IP address and restjavad services on the device are running."
        ]
    },
    "declaration": {
        "$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/schema/base.schema.json",
        "schemaVersion": "1.5.0",
        "class": "Device",
        "Common": {
            "class": "Tenant",
            "provisioningLevels": {
                "class": "Provision",
                "ltm": "nominal"
            },
            "hostname": "bigipos.jthomsonf5.com",
            "myLicense": {
                "class": "License",
                "licenseType": "licensePool",
                "bigIqHost": "10.1.0.227",
                "bigIqUsername": "admin",
                "licensePool": "keypool",
                "reachable": false,
                "hypervisor": "kvm",
                "overwrite": false,
                "unitOfMeasure": "monthly"
            }
        },
        "async": false
    }
}

**Comment by focrensh** [comment] 2019-06-26 20:15
AT-481 opened internally

**Comment by thomsonjames** [comment] 2019-07-22 14:11
Any questions on this? Were you able to reproduce? Hoping to get a fix in next release.

**Comment by focrensh** [comment] 2019-07-22 14:25
No updates currently, still in backlog.

**Comment by seattlevine** [comment] 2019-08-16 17:23
@thomsonjames: Is this a reg key pool?

**Comment by ansmithf5** [comment] 2019-08-20 17:40
Good morning @thomsonjames,

I'm assigned the AT-481 task, and so I'm looking into this issue.

However, I'm unable to reproduce your failure. I've tested your declaration on brand new 13.1 VE BIG-IPs, using a BIG-IQ 7.0 with a license pool, and both 1.7 (DO development version) and 1.5 (The one mentioned in the declaration).

Can you see any differences between your environment and my testing environment? I am also interested in your response to seattlevine's question.

I look forward to your response.

**Comment by thomsonjames** [comment] 2019-08-21 21:09
It was a reg key pool, let me work on getting my repro up and running again. I'll test in 1.5 to see if was accidentally fixed

**Comment by thomsonjames** [comment] 2019-08-22 01:04
Here's my update.  I am using a regkeypool on the BIG-IQ.  The regkeypool component seems to work if the BIG-IP is reachable.

Description attached to help with formatting

In my scenario, the BIG-IP is behind a NAT device and so the mgmt IP address assigned, 192.168.10.209 is not reachable from the BIG-IQ.

To reproduce, I booted up a BIG-IP 14.1, changed the admin and root passwords, disabled gui-setup, temporarily licensed it, installed DO, then took the license off, then sent in the declaration.
[do-fail.txt](https://github.com/F5Networks/f5-declarative-onboarding/files/3527905/do-fail.txt)

**Comment by ansmithf5** [comment] 2019-08-22 17:20
We confirmed using the DO version 1.6.1+ fixes this issue. This fix will be included in later versions of DO as well (e.g. 1.7.0), so keep DO up to date and you should not see this failure.

**Closed by ansmithf5** 2019-08-22 17:20 UTC
Labels: InReview, bug
