### ISSUE TITLE
schema for DO doesn't account for F5 Master Key

### ISSUE THREAD

**Issue by cjenison** [F5Networks/f5-declarative-onboarding#83] opened 2019-10-28 21:47 UTC
there are scenarios where the F5 master key (set using f5mku) is lost during a software upgrade or needs to be set as a result of RMA, etc. Additionally, BIG-IP DNS uses master key as it signs records and there may be reasons to set f5 master key consistently across numerous BIG-IPs deployed globally. For these reasons, DO should allow setting of F5 Master Key as part of on-boarding process.

**Comment by dstokesf5** [comment] 2019-10-28 22:32
Closing as duplicate of #69.

**Closed by dstokesf5** 2019-10-28 22:32 UTC
