### ISSUE TITLE
Add Partition to associate route to traffic-group-local-only (non-floating)

### ISSUE THREAD

**Issue by ab-gmbh** [F5Networks/f5-declarative-onboarding#150] opened 2020-06-11 20:57 UTC
### Is your feature request related to a problem? Please describe.
Setting up a cross AZ HA pair in AWS requires that a default gateway be associated with traffic-group-local-only (non-floating) on both BIG-IP's.

This is needed as the ConfigSync IP of the remote BIG-IP is on a different subnet from the local ConfigSync IP, hence a gateway is needed. If this gateway is set in Common partition, it is associated with traffic-group-1 (floating) and this causes the HA Config sync to throw an error.

### Describe the solution you'd like
The AWS cross AZ HA CFT creates a LOCAL_ONLY partition that is associated with traffic-group-local-only (non-floating) and a default route is added within this partition.

Currently DO is unable to achieve the above and the request is add the above feature. Otherwise DO won't be able to setup a working cross AZ HA pair in AWS.

**Comment by dstokesf5** [comment] 2020-06-24 23:10
This appears to be a duplicate of #141.

**Comment by dstokesf5** [comment] 2020-10-15 00:16
Closing as duplicate.

**Closed by dstokesf5** 2020-10-15 00:16 UTC
Labels: duplicate, enhancement
