### ISSUE TITLE
DO will revoke utility license when overwrite is set to false but leave Big-IP license unmodified 

### ISSUE THREAD

**Issue by megamattzilla** [F5Networks/f5-declarative-onboarding#343] opened 2023-03-14 14:27 UTC
### Environment
 * Declarative Onboarding Version: 1.36
 * BIG-IP Version: 15.1.x 

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "schemaVersion": "1.0.0",
    "class": "Device",
    "async": true,
    "label": "License BIG-IP via BIG-IQ utility license when BIG-IP is not reachable from BIG-IQ",
    "Common": {
        "class": "Tenant",
        "hostname": "bigip.example.com",
        "myLicense": {
            "class": "License",
            "licenseType": "licensePool",
            "bigIqHost": "10.0.1.200",
            "bigIqUsername": "admin",
            "bigIqPassword": "myPassword1",
            "licensePool": "myUtilityLicense",
            "skuKeyword1": "key1",
            "unitOfMeasure": "hourly",
            "reachable": false,
            "hypervisor": "vmware",
            "tenant": "Optional custom descriptor",
            "chargebackTag": "foo-bar",
            "overwrite": false,
            "revokeFrom": "licensePool" 
}
}
}
```

2. Declaration is successful and assigns a license to Big-IP. Big-IQ still has license assigned.  
3. Submit the exact same declaration again. Big-IP will still have license, Big-IQ will show license is revoked.  

This customer occasionally changes the license of a Big-IP when its first built and later added to production. It can be difficult to determine when revokeFrom needs to be supplied in the declaration and when it does not (everything is defined as IaC so they just change the license SKU when it needs to be changed), so they always include revokeFrom allowing DO to decide when to revoke. DO seems to always revoking the currently assigned license from Big-IQ if you re-run the same declaration despite overwrite: false being declared. 

Can DO detect when the license SKU actually changes and only revoke from Big-IQ in that circumstance? 

### Expected Behavior
DO does not revoke the license from Big-IQ. 

### Actual Behavior
DO revokes the license from Big-IQ.

**Comment by seattlevine** [comment] 2023-03-14 16:25
This is working as designed. In the schema:
```
"overwrite": {
    "description": "Whether or not to overwrite the license if the device is already licensed.",
    ...
},
"revokeFrom": {
    "description": "Current license should be revoked from the pool specified. Either just the name of the pool (if old license is on the same BIG-IQ as in the main License section) or full licensePoolInfo (if old license is on a different BIG-IQ)",
    ...
}
```
The two fields don't really have much to do with each other aside from both being properties regarding licensing. `overwrite` simply indicates whether DO should ignore the fact that the device is currently licensed and re-license with the updtaed info. `revokeFrom` means 'revoke the current license'. There is no decision point for either property.

When initially licensing, you want
```
    "overwrite": true,
    "licensePool": "licensePool",
    "skuKeyword1": "key1",
    "unitOfMeasure": "hourly"
```
`overwrite` can be left out here, but it won't affect things either way since the device is not yet licensed.

When switching licenses (maybe to a new pool?) then you want.
```
    "overwrite": true,
    "licensePool": "myUtilityLicense",
    "skuKeyword1": "key1",
    "unitOfMeasure": "hourly",
    "revokeFrom": "licensePool"
```
It sounds like you can already change licensePools, perhaps programmatically, so hopefully you can also set `revokeFrom` appropriately.

**Comment by ghalevy** [comment] 2023-03-15 21:09
> This is working as designed. In the schema:
> 
> ```
> "overwrite": {
>     "description": "Whether or not to overwrite the license if the device is already licensed.",
>     ...
> },
> "revokeFrom": {
>     "description": "Current license should be revoked from the pool specified. Either just the name of the pool (if old license is on the same BIG-IQ as in the main License section) or full licensePoolInfo (if old license is on a different BIG-IQ)",
>     ...
> }
> ```
> 
> The two fields don't really have much to do with each other aside from both being properties regarding licensing. `overwrite` simply indicates whether DO should ignore the fact that the device is currently licensed and re-license with the updtaed info. `revokeFrom` means 'revoke the current license'. There is no decision point for either property.
> 
> When initially licensing, you want
> 
> ```
>     "overwrite": true,
>     "licensePool": "licensePool",
>     "skuKeyword1": "key1",
>     "unitOfMeasure": "hourly"
> ```
> 
> `overwrite` can be left out here, but it won't affect things either way since the device is not yet licensed.
> 
> When switching licenses (maybe to a new pool?) then you want.
> 
> ```
>     "overwrite": true,
>     "licensePool": "myUtilityLicense",
>     "skuKeyword1": "key1",
>     "unitOfMeasure": "hourly",
>     "revokeFrom": "licensePool"
> ```
> 
> It sounds like you can already change licensePools, perhaps programmatically, so hopefully you can also set `revokeFrom` appropriately.

@seattlevine - what if `revokeFrom` is set to an empty string?  Can you confirm the behavior of such a block on a BIGIP which has 

1. Already checked out a license successfully
2. New instantiation

```
      "class": "License",
      "licenseType": "licensePool",
      "bigIqUsername": "bigiq_user",
      "bigIqHost": "bigiq_host",
      "bigIqPassword": "******",
      "overwrite": false,
      "revokeFrom": "",
      "reachable": false,
      "unitOfMeasure": "yearly",
      "tenant": "tenant_name"
      "overwrite": false,
      "licensePool": "license_pool",
      "skuKeyword1": "key1"
```

**Comment by seattlevine** [comment] 2023-03-16 04:00
Some of that depends on where the current license came from, but otherwise, setting `revokeFrom` to an empty string is the same as leaving it out.

**Comment by mdditt2000** [comment] 2023-03-27 17:30
Question answered. Closing issue

**Closed by mdditt2000** 2023-03-27 17:30 UTC
Labels: bug, untriaged
