### ISSUE TITLE
wrong GW IP in declaration leads to DO problems

### ISSUE THREAD

**Issue by vbojko** [F5Networks/f5-declarative-onboarding#18] opened 2019-04-12 18:40 UTC
I send this declaration to a 14.1.03 instance in AWS.
 
{
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/schema/base.schema.json",
    "schemaVersion": "1.0.0",
    "class": "Device",
    "async": true,
    "label": "Basic onboarding",
    "Common": {
        "class": "Tenant",
        "myDns": {
            "class": "DNS",
            "nameServers": [
                "10.140.0.2"
            ],
            "search": [
                "us-west-1.compute.internal"
            ]
        },
        "myNtp": {
            "class": "NTP",
            "servers": [
                "0.pool.ntp.org",
                "1.pool.ntp.org",
                "2.pool.ntp.org"
            ],
            "timezone": "UTC"
        },
        "admin": {
            "class": "User",
            "userType": "regular",
            "password": "1ThisIsMyPassWord2",
            "shell": "bash"
        },
        "myProvisioning": {
            "class": "Provision",
            "ltm": "nominal",
            "gtm": "minimum",
            "apm": "nominal",
            "asm": "nominal",
            "avr": "nominal"
        },
        "internal": {
            "class": "VLAN",
            "tag": 4093,
            "mtu": 1500,
            "interfaces": [
                {
                    "name": "1.2",
                    "tagged": true
                }
            ]
        },
        "internal-self": {
            "class": "SelfIp",
            "address": "10.140.2.100/24",
            "vlan": "internal",
            "allowService": "none",
            "trafficGroup": "traffic-group-local-only"
        },
        "external": {
            "class": "VLAN",
            "tag": 4094,
            "mtu": 1500,
            "interfaces": [
                {
                    "name": "1.1",
                    "tagged": true
                }
            ]
        },
        "external-self": {
            "class": "SelfIp",
            "address": "10.140.1.100/24",
            "vlan": "external",
            "allowService": "none",
            "trafficGroup": "traffic-group-local-only"
        },
        "default": {
            "class": "Route",
            "gw": "10.140.0.1",
            "network": "default",
            "mtu": 1500
        }
    }
}

`

only internal vlan and selfip were configured.
when I send a GET to see the declaration I see this error message:

{
    "code": 422,
    "status": "ERROR",
    "message": "invalid config - rolled back",
    "errors": [
        "01070330:3: Static route gateway 10.140.0.1 is not directly connected via an interface."
    ],
    "declaration": {
        "$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/schema/base.schema.json",
        "schemaVersion": "1.3.0",
        "class": "Device",
        "async": true,
        "label": "Basic onboarding",
        "Common": {
            "class": "Tenant",
            "myDns": {
                "class": "DNS",
                "nameServers": [
                    "10.140.0.2"
                ],
                "search": [
                    "us-west-1.compute.internal"
                ]
            },
            "myNtp": {
                "class": "NTP",
                "servers": [
                    "0.pool.ntp.org",
                    "1.pool.ntp.org",
                    "2.pool.ntp.org"
                ],
                "timezone": "UTC"
            },
            "admin": {
                "class": "User",
                "userType": "regular",
                "shell": "bash"
            },
            "myProvisioning": {
                "class": "Provision",
                "ltm": "nominal",
                "gtm": "minimum",
                "apm": "nominal",
                "asm": "nominal",
                "avr": "nominal"
            },
            "internal": {
                "class": "VLAN",
                "tag": 4093,
                "mtu": 1500,
                "interfaces": [
                    {
                        "name": "1.2",
                        "tagged": true
                    }
                ]
            },
            "internal-self": {
                "class": "SelfIp",
                "address": "10.140.2.100/24",
                "vlan": "internal",
                "allowService": "none",
                "trafficGroup": "traffic-group-local-only"
            },
            "external": {
                "class": "VLAN",
                "tag": 4094,
                "mtu": 1500,
                "interfaces": [
                    {
                        "name": "1.1",
                        "tagged": true
                    }
                ]
            },
            "external-self": {
                "class": "SelfIp",
                "address": "10.140.1.100/24",
                "vlan": "external",
                "allowService": "none",
                "trafficGroup": "traffic-group-local-only"
            },
            "default": {
                "class": "Route",
                "gw": "10.140.0.1",
                "network": "default",
                "mtu": 1500
            }
        }
    }
}

after that I get the same response after I resend the declaration with the correct GW IP.
I am not able to send any updated declaration to DO without getting this error message. I tested it our with different v14.1.03 BIG-IP instances.

**Comment by focrensh** [comment] 2019-04-15 14:23
Ticket AT-191 opened for tracking.

**Comment by seattlevine** [comment] 2019-05-02 22:51
We are unable to reproduce this issue in our upcoming Declarative Onboarding 1.4 code base which resolves problems with deleting objects during a roll back.

**Comment by seattlevine** [comment] 2019-05-07 19:50
Resolved in 1.3.1

**Closed by seattlevine** 2019-05-07 19:50 UTC
Labels: InReview
