### ISSUE TITLE
Order of provisioning not correct - SelfIp and Route objects failed because missing declared VLAN

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-declarative-onboarding#22] opened 2019-04-16 20:46 UTC
The following validated declaration was generated and posted:

```
{
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/schema/base.schema.json",
    "async": false,
    "schemaVersion": "1.0.0",
    "Common": {
        "ntpServers": {
            "timezone": "UTC",
            "class": "NTP",
            "servers": [
                "0.pool.ntp.org",
                "1.pool.ntp.org"
            ]
        },
        "licenseKey": {
            "licenseType": "regKey",
            "class": "License",
            "regKey": "UFRFP-YSMUH-DHDKG-LWORR-VVKWFOJ"
        },
        "configsync": {
            "configsyncIp": "1.1.1.110",
            "class": "ConfigSync"
        },
        "provisioningLevels": {
            "ltm": "nominal",
            "class": "Provision",
            "asm": "minimum"
        },
        "route_192_168_1_102_32": {
            "gw": "1.1.1.88",
            "mtu": 0,
            "class": "Route",
            "network": "192.168.1.102/32"
        },
        "hostname": "testv14-do-additional.sample.openstack.f5se.com",
        "dnsServers": {
            "nameServers": [
                "8.8.8.8"
            ],
            "search": [
                "sample.openstack.f5se.com"
            ],
            "class": "DNS"
        },
        "net_tap58767ee9_ee": {
            "interfaces": [
                {
                    "tagged": false,
                    "name": "1.2"
                }
            ],
            "tag": 4092,
            "class": "VLAN",
            "mtu": 1450
        },
        "tapec56899d-01_default_gw": {
            "gw": "192.168.80.1",
            "mtu": 0,
            "class": "Route",
            "network": "default"
        },
        "selfip_tap7ecab634_a4": {
            "trafficGroup": "traffic-group-local-only",
            "vlan": "net_tap7ecab634_a4",
            "allowService": "all",
            "class": "SelfIp",
            "address": "1.1.1.110/24"
        },
        "net_tap7ecab634_a4": {
            "interfaces": [
                {
                    "tagged": false,
                    "name": "1.1"
                }
            ],
            "tag": 4093,
            "class": "VLAN",
            "mtu": 1450
        },
        "selfip_tap58767ee9_ee": {
            "trafficGroup": "traffic-group-local-only",
            "vlan": "net_tap58767ee9_ee",
            "allowService": "all",
            "class": "SelfIp",
            "address": "192.168.40.53/24"
        },
        "route_192_168_231_0_28": {
            "gw": "1.1.1.105",
            "mtu": 0,
            "class": "Route",
            "network": "192.168.231.0/28"
        },
        "selfip_tapec56899d_01": {
            "trafficGroup": "traffic-group-local-only",
            "vlan": "net_tapec56899d_01",
            "allowService": "all",
            "class": "SelfIp",
            "address": "192.168.80.58/24"
        },
        "net_tapec56899d_01": {
            "interfaces": [
                {
                    "tagged": false,
                    "name": "1.3"
                }
            ],
            "tag": 4091,
            "class": "VLAN",
            "mtu": 1450
        },
        "class": "Tenant",
        "route_192_168_233_0_24": {
            "gw": "1.1.1.102",
            "mtu": 0,
            "class": "Route",
            "network": "192.168.233.0/24"
        }
    },
    "class": "Device",
    "label": "generated from OpenStack metadata"
}
```
generating the following 500 errors stating the a declared VLAN was not defined. It appears that the declared VLAN was not present when the dependant SelfIP and Route object provisioning was attempted.

```
{"code":500,"message":"java.net.ProtocolException: status:500, body:{\"code\":500,\"status\":\"ERROR\",\"message\":\"rollback failed\",\"errors\":[\"01070277:3: The requested vlan, vlangroup or tunnel (/Common/net_tap7ecab634_a4) was not found.\",\"01070277:3: The requested vlan, vlangroup or tunnel (/Common/net_tap7ecab634_a4) was not found.\",\"01070330:3: Static route gateway 1.1.1.88 is not directly connected via an interface.\"],\"declaration\":{\"$schema\":\"https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/schema/base.schema.json\",\"async\":false,\"schemaVersion\":\"1.0.0\",\"Common\":{\"ntpServers\":{\"timezone\":\"UTC\",\"class\":\"NTP\",\"servers\":[\"0.pool.ntp.org\",\"1.pool.ntp.org\"]},\"licenseKey\":{\"licenseType\":\"regKey\",\"class\":\"License\",\"regKey\":\"UFRFP-YSMUH-DHDKG-LWORR-VVKWFOJ\",\"unitOfMeasure\":\"monthly\",\"overwrite\":false},\"configsync\":{\"configsyncIp\":\"1.1.1.110\",\"class\":\"ConfigSync\"},\"provisioningLevels\":{\"ltm\":\"nominal\",\"class\":\"Provision\",\"asm\":\"minimum\"},\"route_192_168_1_102_32\":{\"gw\":\"1.1.1.88\",\"mtu\":0,\"class\":\"Route\",\"network\":\"192.168.1.102/32\"},\"hostname\":\"testv14-do-additional.sample.openstack.f5se.com\",\"dnsServers\":{\"nameServers\":[\"8.8.8.8\"],\"search\":[\"sample.openstack.f5se.com\"],\"class\":\"DNS\"},\"net_tap58767ee9_ee\":{\"interfaces\":[{\"tagged\":false,\"name\":\"1.2\"}],\"tag\":4092,\"class\":\"VLAN\",\"mtu\":1450},\"tapec56899d-01_default_gw\":{\"gw\":\"192.168.80.1\",\"mtu\":0,\"class\":\"Route\",\"network\":\"default\"},\"selfip_tap7ecab634_a4\":{\"trafficGroup\":\"traffic-group-local-only\",\"vlan\":\"net_tap7ecab634_a4\",\"allowService\":\"all\",\"class\":\"SelfIp\",\"address\":\"1.1.1.110/24\"},\"net_tap7ecab634_a4\":{\"interfaces\":[{\"tagged\":false,\"name\":\"1.1\"}],\"tag\":4093,\"class\":\"VLAN\",\"mtu\":1450},\"selfip_tap58767ee9_ee\":{\"trafficGroup\":\"traffic-group-local-only\",\"vlan\":\"net_tap58767ee9_ee\",\"allowService\":\"all\",\"class\":\"SelfIp\",\"address\":\
```

**Comment by jgruber** [comment] 2019-04-17 17:19
I have confirmed that forcing a specific order to the object in the schema will result in a '200' status code and 'message': 'success'. The only changes I made was reording such that the VLAN is defined before the selfIP.  That CAN NOT be a requirement when various code generators, linters, and schema checkers can reorder the declaration.

**Comment by focrensh** [comment] 2019-04-17 17:42
AT-211 for internal testing

**Comment by jgruber** [comment] 2019-04-17 23:30
I just completely refactored my network discover to accommodate do, but it might not be the order.. the second declaration referenced in my earlier comment simply worked on the new POST.

Here is my new refactored declarataion:

```
{
    "schemaVersion": "1.0.0",
    "class": "Device",
    "async": true,
    "label": "generated from OpenStack metadata",
    "Common": {
        "hostname": "testv14-do-licensed.sample.openstack.f5se.com",
        "class": "Tenant",
        "licenseKey": {"licenseType": "regKey", "class": "License", "regKey": "SUGWQ-TRMUB-DOEZF-YFJST-XIBFSRV"},
        "dnsServers": {"nameServers": ["8.8.8.8"], "search": ["sample.openstack.f5se.com"], "class": "DNS"},
        "ntpServers": {"timezone": "UTC", "class": "NTP", "servers": ["0.pool.ntp.org", "1.pool.ntp.org"]},
        "provisioningLevels": {"ltm": "nominal", "class": "Provision", "asm": "minimum"},
        "net_tapcdc06904_eb": {"interfaces": [{"tagged": false, "name": "1.3"}], "tag": 4091, "class": "VLAN", "mtu": 1450},
        "net_tap454961f2_ac": {"interfaces": [{"tagged": false, "name": "1.1"}], "tag": 4093, "class": "VLAN", "mtu": 1450},
        "net_tapda19f2d0_1d": {"interfaces": [{"tagged": false, "name": "1.2"}], "tag": 4092, "class": "VLAN", "mtu": 1450},
        "selfip_tap454961f2_ac": {"trafficGroup": "traffic-group-local-only", "vlan": "net_tap454961f2_ac", "allowService": "all", "class": "SelfIp", "address": "1.1.1.106/24"},
        "selfip_tapcdc06904_eb": {"trafficGroup": "traffic-group-local-only", "vlan": "net_tapcdc06904_eb", "allowService": "all", "class": "SelfIp", "address": "192.168.80.61/24"},
        "selfip_tapda19f2d0_1d": {"trafficGroup": "traffic-group-local-only", "vlan": "net_tapda19f2d0_1d", "allowService": "all", "class": "SelfIp", "address": "192.168.40.55/24"},
        "tapcdc06904-eb_default_gw": {"gw": "192.168.80.1", "mtu": 0, "class": "Route", "network": "default"},
        "route_192_168_1_102_32": {"gw": "1.1.1.88", "mtu": 0, "class": "Route", "network": "192.168.1.102/32"},
        "route_192_168_231_0_28": {"gw": "1.1.1.105", "mtu": 0, "class": "Route", "network": "192.168.231.0/28"},
        "route_192_168_233_0_24": {"gw": "1.1.1.102", "mtu": 0, "class": "Route", "network": "192.168.233.0/24"},
        "configsync": {"configsyncIp": "1.1.1.106", "class": "ConfigSync"}
   }
}
```
with the following result.. leaving my device in a indeterminate REBOOT REQUIRED state again..

```
{
    "code": 422,
    "status": "ERROR",
    "message": "invalid config - rolled back",
    "errors": [
        "01070277:3: The requested vlan, vlangroup or tunnel (/Common/net_tap454961f2_ac) was not found."
    ],
    "declaration": {
        "schemaVersion": "1.0.0",
        "class": "Device",
        "async": true,
        "label": "generated from OpenStack metadata",
        "Common": {
            "hostname": "testv14-do-licensed.sample.openstack.f5se.com",
            "class": "Tenant",
            "licenseKey": {
                "licenseType": "regKey",
                "class": "License",
                "regKey": "SUGWQ-TRMUB-DOEZF-YFJST-XIBFSRV",
                "unitOfMeasure": "monthly",
                "overwrite": false
            },
            "dnsServers": {
                "nameServers": [
                    "8.8.8.8"
                ],
                "search": [
                    "sample.openstack.f5se.com"
                ],
                "class": "DNS"
            },
            "ntpServers": {
                "timezone": "UTC",
                "class": "NTP",
                "servers": [
                    "0.pool.ntp.org",
                    "1.pool.ntp.org"
                ]
            },
            "provisioningLevels": {
                "ltm": "nominal",
                "class": "Provision",
                "asm": "minimum"
            },
            "net_tapcdc06904_eb": {
                "interfaces": [
                    {
                        "tagged": false,
                        "name": "1.3"
                    }
                ],
                "tag": 4091,
                "class": "VLAN",
                "mtu": 1450
            },
            "net_tap454961f2_ac": {
                "interfaces": [
                    {
                        "tagged": false,
                        "name": "1.1"
                    }
                ],
                "tag": 4093,
                "class": "VLAN",
                "mtu": 1450
            },
            "net_tapda19f2d0_1d": {
                "interfaces": [
                    {
                        "tagged": false,
                        "name": "1.2"
                    }
                ],
                "tag": 4092,
                "class": "VLAN",
                "mtu": 1450
            },
            "selfip_tap454961f2_ac": {
                "trafficGroup": "traffic-group-local-only",
                "vlan": "net_tap454961f2_ac",
                "allowService": "all",
                "class": "SelfIp",
                "address": "1.1.1.106/24"
            },
            "selfip_tapcdc06904_eb": {
                "trafficGroup": "traffic-group-local-only",
                "vlan": "net_tapcdc06904_eb",
                "allowService": "all",
                "class": "SelfIp",
                "address": "192.168.80.61/24"
            },
            "selfip_tapda19f2d0_1d": {
                "trafficGroup": "traffic-group-local-only",
                "vlan": "net_tapda19f2d0_1d",
                "allowService": "all",
                "class": "SelfIp",
                "address": "192.168.40.55/24"
            },
            "tapcdc06904-eb_default_gw": {
                "gw": "192.168.80.1",
                "mtu": 0,
                "class": "Route",
                "network": "default"
            },
            "route_192_168_1_102_32": {
                "gw": "1.1.1.88",
                "mtu": 0,
                "class": "Route",
                "network": "192.168.1.102/32"
            },
            "route_192_168_231_0_28": {
                "gw": "1.1.1.105",
                "mtu": 0,
                "class": "Route",
                "network": "192.168.231.0/28"
            },
            "route_192_168_233_0_24": {
                "gw": "1.1.1.102",
                "mtu": 0,
                "class": "Route",
                "network": "192.168.233.0/24"
            },
            "configsync": {
                "configsyncIp": "1.1.1.106",
                "class": "ConfigSync"
            }
        }
    }
}
```

Reposting the identical declaration.. took me through another cycle of restarting services yielding a different error:

```

**Comment by jgruber** [comment] 2019-04-17 23:37
The third post of the exact same declaration yielded:

```
{
    "result": {
        "class": "Result",
        "code": 200,
        "status": "OK",
        "message": "success",
        "errors": []
    },
    "declaration": {
        "schemaVersion": "1.0.0",
        "class": "Device",
        "async": true,
        "label": "generated from OpenStack metadata",
        "Common": {
            "hostname": "testv14-do-licensed.sample.openstack.f5se.com",
            "class": "Tenant",
            "licenseKey": {
                "licenseType": "regKey",
                "class": "License",
                "regKey": "SUGWQ-TRMUB-DOEZF-YFJST-XIBFSRV",
                "unitOfMeasure": "monthly",
                "overwrite": false
            },
            "dnsServers": {
                "nameServers": [
                    "8.8.8.8"
                ],
                "search": [
                    "sample.openstack.f5se.com"
                ],
                "class": "DNS"
            },
            "ntpServers": {
                "timezone": "UTC",
                "class": "NTP",
                "servers": [
                    "0.pool.ntp.org",
                    "1.pool.ntp.org"
                ]
            },
            "provisioningLevels": {
                "ltm": "nominal",
                "class": "Provision",
                "asm": "minimum"
            },
            "net_tapcdc06904_eb": {
                "interfaces": [
                    {
                        "tagged": false,
                        "name": "1.3"
                    }
                ],
                "tag": 4091,
                "class": "VLAN",
                "mtu": 1450
            },
            "net_tap454961f2_ac": {
                "interfaces": [
                    {
                        "tagged": false,
                        "name": "1.1"
                    }
                ],
                "tag": 4093,
                "class": "VLAN",
                "mtu": 1450
            },
            "net_tapda19f2d0_1d": {
                "interfaces": [
                    {
                        "tagged": false,
                        "name": "1.2"
                    }
                ],
                "tag": 4092,
                "class": "VLAN",
                "mtu": 1450
            },
            "selfip_tap454961f2_ac": {
                "trafficGroup": "traffic-group-local-only",
                "vlan": "net_tap454961f2_ac",
                "allowService": "all",
                "class": "SelfIp",
                "address": "1.1.1.106/24"
            },
            "selfip_tapcdc06904_eb": {
                "trafficGroup": "traffic-group-local-only",
                "vlan": "net_tapcdc06904_eb",
                "allowService": "all",
                "class": "SelfIp",
                "address": "192.168.80.61/24"
            },
            "selfip_tapda19f2d0_1d": {
                "trafficGroup": "traffic-group-local-only",
                "vlan": "net_tapda19f2d0_1d",
                "allowService": "all",
                "class": "SelfIp",
                "address": "192.168.40.55/24"
            },
            "tapcdc06904-eb_default_gw": {
                "gw": "192.168.80.1",
                "mtu": 0,
                "class": "Route",
                "network": "default"
            },
            "route_192_168_1_102_32": {
                "gw": "1.1.1.88",
                "mtu": 0,
                "class": "Route",
                "network": "192.168.1.102/32"
            },
            "route_192_168_231_0_28": {
                "gw": "1.1.1.105",
                "mtu": 0,
                "class": "Route",
                "network": "192.168.231.0/28"
            },
            "route_192_168_233_0_24": {
                "gw": "1.1.1.102",
                "mtu": 0,
                "class": "Route",
                "network": "192.168.233.0/24"
            },
            "configsync": {
                "configsyncIp": "1.1.1.106",
                "class": "ConfigSync"
            }
        }
    }
}
```

**Comment by pzolo** [comment] 2019-04-25 15:25
I found https://github.com/F5Networks/f5-declarative-onboarding/issues/32 while trying to find a workaround for this issue. 
In my case I did: 
1- DO with VLAN only 
2- DO with self-ip + route only 
3- DO with rest of elements (DNS, NTP, License, hostname, provisioning) 

On step 3, because I was provisioning multiple modules, I hit https://github.com/F5Networks/f5-declarative-onboarding/issues/21

**Comment by seattlevine** [comment] 2019-04-27 04:39
@jgruber: Are you running on BIG-IP 14.x or 13.x? 

The iControl REST response to a GET request on 14.x is different than on 13.x when there are no instances of the object you are querying. This is causing some issues for DO.

**Comment by seattlevine** [comment] 2019-05-02 17:06
Duplicate of #32

**Closed by seattlevine** 2019-05-02 17:06 UTC
Labels: InReview
