### ISSUE TITLE
Onboarding demand fails occasionally 

### ISSUE THREAD

**Issue by jikui** [F5Networks/f5-declarative-onboarding#77] opened 2019-09-29 04:02 UTC
1) We run into an onboarding error occasonally when we test our WAFAAS project together with  BIGIPVE-14 and BIGIPVE-15 versions. (BIGIP-14.1.0.3-0.0.6  BIGIP-14.1.2  BIGIP14.1.2.1  BIGIP-15.0.1-0.0.11)

2) a) The error message from the DO is,
 
lastErr”: “ONBOARDERROR: Failed to query onboarding status: {\“statusCode\“:400,\“message\“:\“{\\\“code\\\“:400,\\\“message\\\“:\\\“roleEval may not be null.\\\“,\\\“originalRequestBody\\\“:\\\“{}\\\“,\\\“restOperationId\\\“:564,\\\“kind\\\“:\\\“:resterrorresponse\\\“}\“}”
 
b) when we log into the bigip’s UI, the following error hint appears at the top of the UI.
The system must be rebooted for some changes to take effect.
 
c) Our onboarding logic is quite simple, we send the DO onboard demand to the DO  and periodically query the onboard results.  
We also verified that it is no use to enlarge  the query interval.
 
d) The DO rpm we are using is f5-declarative-onboarding-1.5.0-11.noarch.rpm

3) The onboarding declaration is:

{
    "class": "DO",
    "targetHost": "10.250.15.141",
    "targetPort": 443,
    "targetUsername": "admin",
    "targetPassphrase": "admin",
    "targetTimeout": "900",
    "declaration": {
        "schemaVersion": "1.5.0",
        "class": "Device",
        "async": true,
        "label": "Basic onboarding",
        "Common": {
            "class": "Tenant",
            "hostname": "af0593bb-eed2-4f15-bc54-6e9bffab6ccd.f5bigip.local",
            "myLicense": {
                "class": "License",
                "licenseType": "licensePool",
                "bigIqHost": "10.250.11.138",
                "bigIqUsername": "admin",
                "bigIqPassword": "admin",
                "licensePool": "mykeypool",
                "reachable": true,
                "bigIpUsername": "admin",
                "bigIpPassword": "admin"
            },
            "myProvision": {
                "class": "Provision",
                "ltm": "nominal",
                "asm": "nominal"
            },
            "myDns": {
                "class": "DNS",
                "nameServers": [
                    "8.8.8.8"
                ],
                "search": [
                    "openstack.local"
                ]
            },
            "myNtp": {
                "class": "NTP",
                "servers": [
                    "0.pool.ntp.org",
                    "1.pool.ntp.org",
                    "2.pool.ntp.org"
                ],
                "timezone": "UTC"
            },
            "vlan-failover1": {
                "class": "VLAN",
                "interfaces": [
                    {
                        "name": "1.3",
                        "tagged": false
                    }
                ]
            },
            "vlan-internal1": {
                "class": "VLAN",
                "interfaces": [
                    {
                        "name": "1.2",
                        "tagged": false
                    }
                ]
            },
            "vlan-external2": {
                "class": "VLAN",
                "interfaces": [
                    {
                        "name": "1.1",
                        "tagged": false
                    }
                ]
            },
            "selfip-failover1": {
                "class": "SelfIp",
                "vlan": "vlan-failover1",
                "address": "10.250.16.105/24"
            },
            "selfip-internal1": {
                "class": "SelfIp",
                "vlan": "vlan-internal1",
                "address": "10.250.17.152/24"
            },
            "selfip-external2": {
                "class": "SelfIp",
                "vlan": "vlan-external2",
                "address": "10.250.18.127/24"
            },
            "route-external2": {
                "class": "Route",
                "gw": "10.250.18.1",
                "network": "default"
            },
            "configsync": {
                "class": "ConfigSync",
                "configsyncIp": "10.250.16.105"
            }
        }
    }
}

**Comment by dstokesf5** [comment] 2019-10-01 19:51
This sound similar to #73.

**Comment by dstokesf5** [comment] 2019-10-09 18:50
I am going to close this as a duplicate of #73. If you believe this issue is unrelated, please reopen it.

**Closed by dstokesf5** 2019-10-09 18:50 UTC
