### ISSUE TITLE
cloud docs URL to the schema for validation is wrong

### ISSUE THREAD

**Issue by jgruberf5** [F5Networks/f5-declarative-onboarding#115] opened 2020-02-07 21:27 UTC
### Environment
 * Declarative Onboarding Version: 1.10.0-2
 * BIG-IP Version: 14.1.2-0.0.37.0

### Summary
https://clouddocs.f5.com/products/extensions/f5-declarative-onboarding/latest/validate.html

says to add this to you declaration to validate it:

```
"$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/schema/latest/base.schema.json",
```

The source tree was refactored and the doc was not updated. Should read:

```
"$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/src/schema/latest/base.schema.json",
```

**Comment by jgruber** [comment] 2020-02-09 17:03
duplicate of https://github.com/F5Networks/f5-declarative-onboarding/issues/97

**Comment by dstokesf5** [comment] 2020-02-10 18:55
Closing as a duplicate.

**Closed by dstokesf5** 2020-02-10 18:55 UTC
Labels: bug, duplicate
