### ISSUE TITLE
declaration fails when DHCP is disabled

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-declarative-onboarding#43] opened 2019-06-17 20:11 UTC
Ran the following on a 1NIC deployment before making a declaration:

tmsh modify sys global-settings mgmt-dhcp disabled
tmsh modify sys db provision.1nicautoconfig value disable
tmsh modify sys db provision.1nic value forced_enable
tmsh modify sys httpd ssl-port 8443
tmsh modify net self-allow defaults add { tcp:8443 }
tmsh create sys management-ip 192.168.80.53/24 description 'provisioned by tmos_static_mgmt'
tmsh create net vlan internal { interfaces replace-all-with { 1.0 { } } tag 4094 mtu 1450 }
tmsh create net self self_1nic { address 192.168.80.53/24 allow-service default vlan internal }
tmsh create sys management-route default gateway 192.168.80.1
tmsh create net route default network default gw 192.168.80.1
tmsh save sys config base

The declaration then yields:

{"code":500,"message":"java.net.ProtocolException: status:500, body:{\"id\":\"e237d5e3-53ba-401d-8ce9-0640cfba215c\",\"selfLink\":\"https://localhost/mgmt/shared/declarative-onboarding/task/e237d5e3-53ba-401d-8ce9-0640cfba215c\",\"code\":500,\"status\":\"ERROR\",\"message\":\"invalid config - rolled back\",\"errors\":[\"tryUntil: max tries reached: dhclient status is * dhclient.service - SYSV: dhclient automatically configures the management interface when DHCP is available.\\n   Loaded: loaded (/etc/rc.d/init.d/dhclient; bad; vendor preset: disabled)\\n   Active: active (exited) since Mon 2019-06-17 12:25:42 PDT; 1min 4s ago\\n     Docs: man:systemd-sysv-generator(8)\\n  Process: 18253 ExecStop=/etc/rc.d/init.d/dhclient stop (code=exited, status=7)\\n  Process: 18290 ExecStart=/etc/rc.d/init.d/dhclient start (code=exited, status=0/SUCCESS)\\n\\nJun 17 12:25:42 localhost.localdomain systemd[1]: Starting SYSV: dhclient automatically configures the management interface when DHCP is available....\\nJun 17 12:25:42 localhost.localdomain dhclient[18290]: Current management-ip configuration mode for IPV4 is: Static.\\nJun 17 12:25:42 localhost.localdomain systemd[1]: Started SYSV: dhclient automatically configures the management interface when DHCP is available..\\n\"],\"result\":{\"class\":\"Result\",\"code\":500,\"status\":\"ERROR\",\"message\":\"invalid config - rolled back\",\"errors\":[\"tryUntil: max tries reached: dhclient status is * dhclient.service - SYSV: dhclient automatically configures the management interface when DHCP is available.\\n   Loaded: loaded (/etc/rc.d/init.d/dhclient; bad; vendor preset: disabled)\\n   Active: active (exited) since Mon 2019-06-17 12:25:42 PDT; 1min 4s ago\\n     Docs: man:systemd-sysv-generator(8)\\n  Process: 18253 ExecStop=/etc/rc.d/init.d/dhclient stop (code=exited, status=7)\\n  Process: 18290 ExecStart=/etc/rc.d/init.d/dhclient start (code=exited, status=0/SUCCESS)\\n\\nJun 17 12:25:42 localhost.localdomain systemd[1]: Starting SYSV: dhclient automatically configures the

This isn't an error when DHCP is disabled.

This is version f5-declarative-onboarding-1.5.0-8.

I assume this is related to the new DNS/NTP checks for DHCP when declared:

Mon, 17 Jun 2019 19:35:22 GMT - fine: [f5-declarative-onboarding: systemHandler.js] Checking DNS.
Mon, 17 Jun 2019 19:35:22 GMT - fine: [f5-declarative-onboarding: restWorker.js] list localhost /tm/sys/management-dhcp/sys-mgmt-dhcp-config
Mon, 17 Jun 2019 19:35:22 GMT - fine: [f5-declarative-onboarding: restWorker.js] {"kind":"tm:sys:management-dhcp:management-dhcpstate","name":"sys-mgmt-dhcp-config","fullPath":"sys-mgmt-dhcp-config","generation":0,"selfLink":"https://localhost/mgmt/tm/sys/management-dhcp/sys-mgmt-dhcp-config?ver=14.1.0.5","requestOptions":["subnet-mask","broadcast-address","routers","domain-name","domain-name-servers","host-name","ntp-servers","interface-mtu"]}
Mon, 17 Jun 2019 19:35:22 GMT - fine: [f5-declarative-onboarding: restWorker.js] modify localhost /tm/sys/management-dhcp/sys-mgmt-dhcp-config {"requestOptions":["subnet-mask","broadcast-address","routers","host-name","ntp-servers","interface-mtu"]}
Mon, 17 Jun 2019 19:35:23 GMT - fine: [f5-declarative-onboarding: restWorker.js] {"kind":"tm:sys:management-dhcp:management-dhcpstate","name":"sys-mgmt-dhcp-config","fullPath":"sys-mgmt-dhcp-config","generation":76,"selfLink":"https://localhost/mgmt/tm/sys/management-dhcp/sys-mgmt-dhcp-config?ver=14.1.0.5","requestOptions":["subnet-mask","broadcast-address","routers","host-name","ntp-servers","interface-mtu"]}
Mon, 17 Jun 2019 19:35:23 GMT - fine: [f5-declarative-onboarding: restWorker.js] create localhost /tm/sys/service {"command":"restart","name":"dhclient"}
Mon, 17 Jun 2019 19:35:23 GMT - fine: [f5-declarative-onboarding: restWorker.js] {"kind":"tm:sys:service:restartstate","command":"restart","name":"dhclient","commandResult":"Stopping dhclient (via systemctl):  [  OK  ]\r\nStarting dhclient (via systemctl):  [  OK  ]\r\n"}
Mon, 17 Jun 2019 19:35:23 GMT - fine: [f5-declarative-onboarding: restWorker.js] list localhost /tm/sys/service/dhclient/stats
Mon, 17 Jun 2019 19:35:23 GMT - fine: [f5-declarative-onboarding: restWorker.js] {"kind":"tm:sys:service:servicestats","generation":0,"selfLink":"https://localhost/mgmt/tm/sys/service/dhclient/stats?ver=14.1.0.5","apiRawValues":{"apiAnonymous":"* dhclient.service - SYSV: dhclient automatically configures the management interface when DHCP is available.\n   Loaded: loaded (/etc/rc.d/init.d/dhclient; bad; vendor preset: disabled)\n   Active: active (exited) since Mon 2019-06-17 12:35:23 PDT; 89ms ago\n     Docs: man:systemd-sysv-generator(8)\n  Process: 17732 ExecStart=/etc/rc.d/init.d/dhclient start (code=exited, status=0/SUCCESS)\n\nJun 17 12:35:23 test1nicwaf-waf-instance-ntbdmrttkyqd.sample.openstack.f5se.com systemd[1]: Starting SYSV: dhclient automatically configures the management interface when DHCP is available....\nJun 17 12:35:23 test1nicwaf-waf-instance-ntbdmrttkyqd.sample.openstack.f5se.com dhclient[17732]: Current management-ip configuration mode for IPV4 is: Static.\nJun 17 12:35:23 test1nicwaf-waf-instance-ntbdmrttkyqd.sample.openstack.f5se.com systemd[1]: Started SYSV: dhclient automatically configures the management interface when DHCP is available..\n"}}
Mon, 17 Jun 2019 19:35:23 GMT - finest: [f5-declarative-onboarding: restWorker.js] tryUntil: got error {}
Mon, 17 Jun 2019 19:35:23 GMT - finest: [f5-declarative-onboarding: restWorker.js] typeof err object
Mon, 17 Jun 2019 19:35:23 GMT - finer: [f5-declarative-onboarding: restWorker.js] tryUntil error: dhclient status is * dhclient.service - SYSV: dhclient automatically configures the management interface when DHCP is available.
   Loaded: loaded (/etc/rc.d/init.d/dhclient; bad; vendor preset: disabled)
   Active: active (exited) since Mon 2019-06-17 12:35:23 PDT; 89ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 17732 ExecStart=/etc/rc.d/init.d/dhclient start (code=exited, status=0/SUCCESS)

**Comment by jgruber** [comment] 2019-06-17 20:24
Just finished another test.. The error does not occur is DNS / NTP were previously manually configured.

**Comment by jgruber** [comment] 2019-06-18 11:38
Have a workaround for my Heat templates using the f5 cloudinit modules. It confirms that with DHCP for the management interface disable, manually setting DNS and NTP settings before issuing your DO declaration stops DO from checking the status of the dhclient service.. which is what is causing the problem.

Added this to run before my DO declaration:

tmos_static_mgmt:
  enabled: true
  ip: __vip_selfip__/__vip_mask__
  mtu: __vip_mtu__
  gw: __default_gateway__
  post_onboard_enabled: true
  post_omboard_commands:
    - tmsh modify sys dns name-servers replace-all-with { __dns_server__ }
    - tmsh modify sys dns search replace-all-with { example.openstack.com }
    - tmsh modify sys ntp timezone UTC
    - tmsh modify sys ntp servers replace-all-with { 0.pool.ntp.org 1.pool.ntp.org }

One these services were manually configured, issue clears.. We need to have the service check see if mgmt DHCP is disable before doing the service check. If it is, skip the check/dhclient configuration configuration.

**Comment by jgruber** [comment] 2019-06-18 12:32
Why was this closed?... There still a bug in DO. I didn't see anything in the commit which would prevent the dhclient service check.  I posted a 'work around', not a fix. DO should either not be checking the service status of dhclient if DHCP has been disabled, or it should understand how to read the service check and understand DHCP has been disabled. Right now DO is erroring out with a valid configuration.

**Comment by jgruber** [comment] 2019-06-18 12:44
So there is a timing error where this can still occur...  We really do need DO to fix/skip the dhclient check if dhcp service is disabled. My work around did not work in all my test runs.

Same error:

`{"code":500,"message":"java.net.ProtocolException: status:500, body:{\"id\":\"a753f25d-361e-4790-b7f1-07923d8d5e7d\",\"selfLink\":\"https://localhost/mgmt/shared/declarative-onboarding/task/a753f25d-361e-4790-b7f1-07923d8d5e7d\",\"code\":500,\"status\":\"ERROR\",\"message\":\"invalid config - rolled back\",\"errors\":[\"tryUntil: max tries reached: dhclient status is * dhclient.service - SYSV: dhclient automatically configures the management interface when DHCP is available.\\n   Loaded: loaded (/etc/rc.d/init.d/dhclient; bad; vendor preset: disabled)\\n   Active: active (exited) since Tue 2019-06-18 12:39:59 UTC; 1min 4s ago\\n     Docs: man:systemd-sysv-generator(8)\\n  Process: 17565 ExecStart=/etc/rc.d/init.d/dhclient start (code=exited, status=0/SUCCESS)\\n\\nJun 18 12:39:59 localhost.localdomain systemd[1]: Starting SYSV: dhclient automatically configures the management interface when DHCP is available....\\nJun 18 12:39:59 localhost.localdomain dhclient[17565]: Current management-ip configuration mode for IPV4 is: Static.\\nJun 18 12:39:59 localhost.localdomain systemd[1]: Started SYSV: dhclient automatically configures the management interface when DHCP is available..\\n\"],\"result\":{\"class\":\"Result\",\"code\":500,\"status\":\"ERROR\",\"message\":\"invalid config - rolled back\",\"errors\":[\"tryUntil: max tries reached: dhclient status is * dhclient.service - SYSV: dhclient automatically configures the management interface when DHCP is available.\\n   Loaded: loaded (/etc/rc.d/init.d/dhclient; bad; vendor preset: disabled)\\n   Active: active (exited) since Tue 2019-06-18 12:39:59 UTC; 1min 4s ago\\n     Docs: man:systemd-sysv-generator(8)\\n  Process: 17565 ExecStart=/etc/rc.d/init.d/dhclient start (code=exited, status=0/SUCCESS)\\n\\nJun 18 12:39:59 localhost.localdomain systemd[1]: Starting SYSV: dhclient automatically configures the management interface when DHCP is available....\\nJun 18 12:39:59 localhost.localdomain dhclient[17565]: Current management-ip configuration mode for IPV4 is: Static`

**Comment by focrensh** [comment] 2019-06-18 15:00
AT-453 for tracking

**Comment by seattlevine** [comment] 2019-06-18 15:50
Sorry about the closure - GitHub closed it when we pushed because it was referenced in a commit message as being fixed.

**Comment by vsnine** [comment] 2019-06-21 20:31
I think I ran into something similar. Have some scripts that bootstrap a fresh VM and when running DO via the docker container against the system, i get the following outputs.

BIG-IP Version 13.1.0.7
DO Docker version: 1.5.0

`Fri, 21 Jun 2019 20:18:08 GMT - fine: [f5-declarative-onboarding: systemHandler.js] Checking DNS.
Fri, 21 Jun 2019 20:18:08 GMT - fine: [f5-declarative-onboarding: restWorker.js] list 10.1.1.2 /tm/sys/management-dhcp/sys-mgmt-dhcp-config
Fri, 21 Jun 2019 20:18:08 GMT - fine: [f5-declarative-onboarding: restWorker.js] {"kind":"tm:sys:management-dhcp:management-dhcpstate","name":"sys-mgmt-dhcp-config","fullPath":"sys-mgmt-dhcp-config","generation":1,"selfLink":"https://localhost/mgmt/tm/s
ys/management-dhcp/sys-mgmt-dhcp-config?ver=13.1.0.7","requestOptions":["subnet-mask","broadcast-address","routers","domain-name","domain-name-servers","host-name","ntp-servers","interface-mtu"]}
Fri, 21 Jun 2019 20:18:08 GMT - fine: [f5-declarative-onboarding: restWorker.js] modify 10.1.1.2 /tm/sys/management-dhcp/sys-mgmt-dhcp-config {"requestOptions":["subnet-mask","broadcast-address","routers","host-name","ntp-servers","interface-mtu"]}
Fri, 21 Jun 2019 20:18:09 GMT - fine: [f5-declarative-onboarding: restWorker.js] {"kind":"tm:sys:management-dhcp:management-dhcpstate","name":"sys-mgmt-dhcp-config","fullPath":"sys-mgmt-dhcp-config","generation":145,"selfLink":"https://localhost/mgmt/tm
/sys/management-dhcp/sys-mgmt-dhcp-config?ver=13.1.0.7","requestOptions":["subnet-mask","broadcast-address","routers","host-name","ntp-servers","interface-mtu"]}
Fri, 21 Jun 2019 20:18:09 GMT - fine: [f5-declarative-onboarding: restWorker.js] create 10.1.1.2 /tm/sys/service {"command":"restart","name":"dhclient"}
Fri, 21 Jun 2019 20:18:09 GMT - fine: [f5-declarative-onboarding: restWorker.js] {"kind":"tm:sys:service:restartstate","command":"restart","name":"dhclient","commandResult":"Current management-ip configuration mode is: Static.\n"}
Fri, 21 Jun 2019 20:18:09 GMT - fine: [f5-declarative-onboarding: restWorker.js] list 10.1.1.2 /tm/sys/service/dhclient/stats
Fri, 21 Jun 2019 20:18:09 GMT - fine: [f5-declarative-onboarding: restWorker.js] {"kind":"tm:sys:service:servicestats","generation":0,"selfLink":"https://localhost/mgmt/tm/sys/service/dhclient/stats?ver=13.1.0.7","apiRawValues":{"apiAnonymous":"dhclient
 is stopped\n"}}
Fri, 21 Jun 2019 20:18:09 GMT - finest: [f5-declarative-onboarding: restWorker.js] tryUntil: got error {}
Fri, 21 Jun 2019 20:18:09 GMT - finest: [f5-declarative-onboarding: restWorker.js] typeof err object
Fri, 21 Jun 2019 20:18:09 GMT - finer: [f5-declarative-onboarding: restWorker.js] tryUntil error: dhclient status is dhclient is stopped
 tries left: 30
Fri, 21 Jun 2019 20:18:09 GMT - finest: [f5-declarative-onboarding: restWorker.js] tryUntil: retryOrReject: numRemaining: 30 , code: {} , message: dhclient status is dhclient is stopped
`

**Comment by ansmithf5** [comment] 2019-06-25 16:43
@jgruber, what is the declaration you're using to get this issue?

I've tried a couple different declarations and am unable to reproduce the issue. So I'm not sure if it is an issue with my environment or the declaration(s) I'm using.

Thank you very much!

**Comment by jgruber** [comment] 2019-06-25 19:31
Confirmed with SP architect. Disabling DHCP on the mgmt interface is a VERY common practice. 

All you need to do is disable DHCP on the mgmt interface before you declare DO with the DHCP config check for DNS settings.. you get:

```
Tue, 25 Jun 2019 19:05:56 GMT - severe: [appsvcs] {"message":"Error: Command failed: ls /var/config/rest/iapps/f5-appsvcs/encryptedDeclaration\nls: cannot access /var/config/rest/iapps/f5-appsvcs/encryptedDeclaration: No such file or directory\n","code":"2","level":"error"}

Tue, 25 Jun 2019 19:06:19 GMT - finest: [f5-declarative-onboarding: restWorker.js] tryUntil: got error {}

Tue, 25 Jun 2019 19:06:19 GMT - finer: [f5-declarative-onboarding: restWorker.js] tryUntil error: dhclient status is * dhclient.service - SYSV: dhclient automatically configures the management interface when DHCP is avail
```

in /var/log/restnoded/restnoded.log

**Comment by jgruber** [comment] 2019-06-25 19:51
in systemHandler.js there are two places (handleDNS and handle NTP) where the promise chain calls disableDhcpOptions. If /sys/management-dhcp request-options still have 'domain-name-servers' or 'ntp-servers' (depending on what is declared) the requiresDhcpRestart variable is set to true and the restartDhcp method is called.

If DHCP has been disable.. restarting the service will not show it 'running'.. because it is disabled. That's you bug.

You need to see if the service is disabled (check /sys/global-settings/mgmt-dhcp is enabled or disabled) before you decide to call restartDhcp.

Simple to fix...

**Comment by cpjs** [comment] 2019-06-26 13:27
I am seeing the same problem here.

BIG-IP 14.1 and BIG-IP 15.0
DO 1.5.0

I've tried setting dummy dns/ntp values like suggested above:

tmsh modify sys dns name-servers replace-all-with { dns_server }
tmsh modify sys dns search replace-all-with { example.openstack.com }
tmsh modify sys ntp timezone UTC
tmsh modify sys ntp servers replace-all-with { 0.pool.ntp.org 1.pool.ntp.org }

But that hasn't resolved the issue. The error output returned from /mgmt/shared/declarative-onboarding/task/<id> is:

    "errors": [
        "tryUntil: max tries reached: dhclient status is * dhclient.service - SYSV: dhclient automatically configures the management interface when DHCP is available.\n   Loaded: loaded (/etc/rc.d/init.d/dhclient; bad; vendor preset: disabled)\n   Active: active (exited) since Wed 2019-06-26 13:22:01 UTC; 1min 4s ago\n     Docs: man:systemd-sysv-generator(8)\n  Process: 22442 ExecStop=/etc/rc.d/init.d/dhclient stop (code=exited, status=7)\n  Process: 22478 ExecStart=/etc/rc.d/init.d/dhclient start (code=exited, status=0/SUCCESS)\n\nJun 26 13:22:01 localhost.localdomain systemd[1]: Starting SYSV: dhclient automatically configures the management interface when DHCP is available....\nJun 26 13:22:01 localhost.localdomain dhclient[22478]: Current management-ip configuration mode for IPV4 is: Static.\nJun 26 13:22:01 localhost.localdomain systemd[1]: Started SYSV: dhclient automatically configures the management interface when DHCP is available..\n"
    ],

**Comment by ansmithf5** [comment] 2019-06-27 18:26
Thank you for your insight into this! Yeah there was previously no checking to determine the state of DHCP before the service was restarted. I've made the change, tested it, and merged it into DO's development branch. The next release will have this fix.

**Comment by thomsonjames** [comment] 2019-07-30 19:09
Did this fix make it into 1.6?

**Comment by focrensh** [comment] 2019-07-30 19:45
Yes, it was included in DO1.6 release.

**Closed by focrensh** 2019-07-30 19:45 UTC
Labels: InReview, bug

**Comment by onurbrc** [comment] 2019-08-16 15:37
@focrensh I have the DO 1.6 version. 

```
"version": "1.6.0",
"release": "1",
"schemaCurrent": "1.6.0",
"schemaMinimum": "1.0.0"
```
But I still have the same errors mentioned  above when I'm trying to config NTP and DNS. Before the retries start and the rollback takes place, I have these logs: 
```
Fri, 16 Aug 2019 14:52:36 GMT - finest: socket 376 opened
Fri, 16 Aug 2019 14:52:36 GMT - finest: [f5-declarative-onboarding: restWorker.js] Got onboarding request.
Fri, 16 Aug 2019 14:52:36 GMT - fine: [f5-declarative-onboarding: restWorker.js] Onboard starting for task 50de2707-c5d9-40b6-b549-1c7ed533dd3d
Fri, 16 Aug 2019 14:52:46 GMT - info: [f5-declarative-onboarding: doUtil.js] Platform: CONTAINER
Fri, 16 Aug 2019 14:52:46 GMT - finest: [f5-declarative-onboarding: restWorker.js] done w/ initial accout setup
Fri, 16 Aug 2019 14:52:47 GMT - info: [f5-declarative-onboarding: restWorker.js] This is a BIG-IP
Fri, 16 Aug 2019 14:52:47 GMT - info: [f5-declarative-onboarding: restWorker.js] Waiting for device to be ready.
Fri, 16 Aug 2019 14:52:47 GMT - fine: [f5-declarative-onboarding: restWorker.js] list localhost /shared/echo/available
Fri, 16 Aug 2019 14:52:47 GMT - fine: [f5-declarative-onboarding: restWorker.js] {}
Fri, 16 Aug 2019 14:52:47 GMT - fine: [f5-declarative-onboarding: restWorker.js] list localhost /shared/identified-devices/config/device-info/available
Fri, 16 Aug 2019 14:52:47 GMT - fine: [f5-declarative-onboarding: restWorker.js] {}
Fri, 16 Aug 2019 14:52:47 GMT - fine: [f5-declarative-onboarding: restWorker.js] list localhost /tm/sys/available
Fri, 16 Aug 2019 14:52:47 GMT - finest: [f5-declarative-onboarding: restWorker.js] tryUntil: got error {"code":404}
Fri, 16 Aug 2019 14:52:47 GMT - finest: [f5-declarative-onboarding: restWorker.js] typeof err object
Fri, 16 Aug 2019 14:52:47 GMT - finer: [f5-declarative-onboarding: restWorker.js] tryUntil error: Public URI path not registered: /tm/sys/available tries left: 0
Fri, 16 Aug 2019 14:52:47 GMT - finest: [f5-declarative-onboarding: restWorker.js] tryUntil: retryOrReject: numRemaining: 0 , code: 404 , message: Public URI path not registered: /tm/sys/available
Fri, 16 Aug 2019 14:52:47 GMT - finer: [f5-declarative-onboarding: restWorker.js] Max tries reached.
Fri, 16 Aug 2019 14:52:47 GMT - finest: [f5-declarative-onboarding: restWorker.js] tryUntil: got error {"code":404,"message":"tryUntil: max tries reached: Public URI path not registered: /tm/sys/available","name":"Error"}
Fri, 16 Aug 2019 14:52:47 GMT - finest: [f5-declarative-onboarding: restWorker.js] typeof err object
Fri, 16 Aug 2019 14:52:47 GMT - finer: [f5-declarative-onboarding: restWorker.js] tryUntil error: tryUntil: max tries reached: Public URI path not registered: /tm/sys/available tries left: 90
Fri, 16 Aug 2019 14:52:47 GMT - finest: [f5-declarative-onboarding: restWorker.js] tryUntil: retryOrReject: numRemaining: 90 , code: 404 , message: tryUntil: max tries reached: Public URI path not registered: /tm/sys/available
Fri, 16 Aug 2019 14:52:52 GMT - finest: socket 376 closed

[...]

Fri, 16 Aug 2019 14:58:15  GMT - info: [f5-declarative-onboarding: restWorker.js] Rolling back configuration
```
Any tips?

**Comment by focrensh** [comment] 2019-08-16 18:25
@onurbrc , will you please open a new issue with your declaration that refers back to this issue. We can then look through it and see if this is the same use case / issue.
